### PR TITLE
fix: the explanation error popup not centered with different screen resolutions

### PR DESCRIPTION
**Pull request by allkhor**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.

**What kind of change does this PR introduce?**
Bug fix.

**Does this PR introduce a breaking change?**
No

## New feature or change ##

**What is the current behavior?** 

**What is the new behavior?**

### CODE REVIEW

**Comment by pycbouh** [comment]
You don't need to do this on the resized signal. The popup has a fixed size, you can just update the anchors in the scene (which we forgot to do when the adjusted the size of the panel). For a more dynamic solution, setting the anchors on about to show should be more appropriate.

**Comment by NathanLovato** [comment]
Yup, you could just use the full screen layout for the color rect in OutputConsole.tscn, and possibly a CenterContainer with the overlay popup as a child. We generally favor declarative options for UI (-> using nodes and node settings in the scene over gdscript).

**Comment by allkhor** [comment]
Setting anchor to the scene it's first was I do, but the ColorRect is child of container and when visibility manually changed anchor was gonna reset to zero. I think on desktop platform when explanation popup was opened and user has change the window size, popup must be recalculated to be centered on the screen like other UI elements fit free space. I can update anchor on ColorRect, but this not covered case when user change the windows size, it's not affected html export, but only desktop, WDYT?

**Comment by NathanLovato** [comment]
Got it, I hadn't noticed it was in the output console scene (there's another somewhere else). The PR fixes the issue so let's merge it. Thanks much for the help once more!

**Pull request merged**
