### PR TITLE
content: add lesson 12

### PR DESCRIPTION
**Pull request by johnnygossdev**
- [x] Write lesson
- [x] Add practices
- [x] ~~Add Shadowed Variable error information~~
- [x] Add extra test to account for SHADOWED_VARIABLE warning

**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.

**What kind of change does this PR introduce?**
This PR adds
- Lesson 12: **Using variables to make code easier to read**.
- Three practices

See [the curriculum](https://github.com/GDQuest/learn-gdscript/blob/main/course/README.md#lesson-12-using-variables-to-make-code-easier-to-read) for more information.

### CODE REVIEW

**Comment by Xananax** [comment]
Not much to say, this is good! Pleasant to read and clear.

One potential improvement would be to explain shadowing somewhat, specially that it is likely to be a mistake people can do in exercise 2.

image

Alternatively, or additionally, we can also add it to the important errors to explain.

**Comment by johnnygossdev** [comment]
My initial thought is filling in the error message would be enough, rather than explaining this specific error in the lesson. I'd just worry about overloading the student.

**Comment by johnnygossdev** [comment]
I added a test to check for too many variable assignments to get around the SHADOWED_VARIABLE warning until another system is in place. Ready for a final check and merge @Xananax.

**Comment by Xananax** [comment]
I've brought some very minor additional changes, otherwise, LGTM

**Comment by Xananax** [comment]
We should make an issue about better warnings handling app-wide though

**Pull request merged**
