### PR TITLE
feat: make glossary entries work in other languages

### PR DESCRIPTION
**Pull request by Wolfy7**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.

Related issue (if applicable): #685

**What kind of change does this PR introduce?**
Emit the "translation_changed" signal from the TranslationManager when the language is set.
Listen to this signal in UILesson.gd and trigger the new defined function `_underline_glossary_entries` for Underline glossary entries.

### CODE REVIEW

**Comment by Wolfy7** [comment]
If changes are okay, please label it for **Hacktoberfest**
Thank you 😊

**Comment by NathanLovato** [comment]
Thanks for the help! This currently doesn't work because it tries to underline the English keywords in other languages. For example, in Spanish, "function" becomes "función" so we would need to target this keyword. To achieve that,  you'll need to update `_glossary.replace_matching_terms()` (or generally the glossary script) to compile and use regexes in the target language.

The way it works right now is we make a big regex with all the glossary terms to find and use a regex replace to find and underline them. But it's only done in English.

**Comment by Wolfy7** [comment]
Yes, you right. 
This will just fix that if you switch the language from english to another language and back again to english, that then the word from the glossary are underlined again.

To handle this for other languages like Spanish, there are more work to do. As you already wrote.

I will think about it how to archive this, if you have already something in mind i would appreciate if you shared it with me 😊

Should this done with an addtional PR or in this one?

Thank you for your help.

**Comment by NathanLovato** [comment]
Thanks. I'd prefer this to be done in this PR because otherwise, fixing this bug the way it's currently done will introduce a separate bug for people using other languages. We might as well handle both cases at once.

**Comment by Wolfy7** [comment]
If we create/read the glossary after TranslationManager is ready and also recreate it after a languange switch. 
It should work without changing `_glossary.replace_matching_terms()`

But not completely sure if these changes are wanted.

**Comment by NathanLovato** [comment]
Rebuilding the glossary on a language change and changing the highlighted keywords at that time sounds good to me, it's a good approach!

**Comment by Wolfy7** [comment]
I did these changes in my last commit https://github.com/GDQuest/learn-gdscript/pull/687/commits/959c6701637fdab074be667a294cd218ced2d0f3

In my test it works as expected:
image

image

**Comment by NathanLovato** [comment]
Great work André. The issue was small, you were trying to translate the capitalized term in the glossary entries but then that would not match translation strings.

I just moved the capitalize() call after the tr() call.

image

**Comment by Wolfy7** [comment]
Thank you Nathan.

Just want to use the change, writing with you. To say **Thank you!** of course to you and the whole GDQuest-Team.
I follow your YouTube-Channel since years, and every video is a pleasure to watch.

But also to all the work you  (GDQuest) put into the OpenSource-Community, the GameDevelopment community.
I'm pleasured to work on your amazing products.

So, yeah im not so good with words. But wanted to let you know. An just once again **Thank you.**.

**Comment by NathanLovato** [comment]
Thanks :)

**Pull request merged**
