### PR TITLE
fix: reverse logic, should checked that desired_inventory has all keys

### LINKED ISSUE #904: Lesson 24, practice 1 softlocks with extra key-value pairs
In practice 1 of lesson 24 you're asked to create a dictionary with certain keys and values. Adding extra key-value pairs causes the game to get stuck while it says "Running Tests...".

**How to reproduce**
-Go to lesson 24
-Go to practice 1
-Press "Run" with the following code: `var inventory = {"healing heart": 3, "gems": 9, "sword": 1, "extra": 4}`

**Expected behavior**
The game should either accept the solution or give an error message.

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Firefox

### PR DESCRIPTION
**Pull request by Wolfy7**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.

fix #904 

## New feature or change ##

**What is the current behavior?** 

See #904 
App will crash due to error:

`Invalid get index 'extra' (on base: 'Dictionary').`

**What is the new behavior?**

App will not crash and tests will fail correctly.

image

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thank you very much for taking the time to fix bugs here! I'm sorry I'm not getting back to you quickly; I was at the Godot conference this weekend and came back sick. I'll test and merge your contributions as soon as possible.

**Comment by Wolfy7** [comment]
> Thank you very much for taking the time to fix bugs here! I'm sorry I'm not getting back to you quickly; I was at the Godot conference this weekend and came back sick. I'll test and merge your contributions as soon as possible.

No worries. Take your time.

Nice, hope it was a nice trip / event the Godot conference but sad to hear that you came back sick. 
Get well soon

**Comment by NathanLovato** [comment]
Thanks so much once again! I'm very grateful that you're taking the time to make this app better for everyone.

**Comment by Wolfy7** [comment]
Oh no, I have to thank you. For making this software open source so that people like me, for example, can learn from it and with it.

**Pull request merged**
