### PR TITLE
improvement: animate quiz resizing

### PR DESCRIPTION
**Pull request by mathmods**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.
    - [ ] You updated the docs or changelog.

Related issue (if applicable): #15 

**What kind of change does this PR introduce?**
Animates resizes of Quiz content blocks. Reacts upon any change of choice view or result view and will proceed to fit (if they are visible).
Almost the same as #234 except with proper spacing on some content.

This PR changes the Quiz Base UI to use a Control node with clip content on to contain margin containers. It reacts to the minimum size changes of the margin containers to determine the size it's supposed to animate to.

**Does this PR introduce a breaking change?**
No

## New feature or change ##

**What is the current behavior?** 
Instantaneous jumps to new size.

**What is the new behavior?**
Animated size changes of rectangle size to fit the current view.

**Other information**
There are now 2 margin containers to ensure that one view doesn't affect the size of the other view. This helps remove guesswork from resizing animations. (And massively improves readability of the code.)

### CODE REVIEW

**Comment by mathmods** [comment]
@NathanLovato While this new attempt does address the issue with the last one, I'm wondering what looked best:

* The new one where the clip border is at the bottom of the UI, essentially making no boundary between the edge and other content during resizing.
* The old one where the clip border was at the margins of the container, making text appear/disappear inside the UI avoiding temporary no-margin times.

Personally I found the old one better due to the buttons on the bottom looking quite bad when pushed to the edge of the UI.
I have already implemented it (on local repository), but I'm getting the feeling that it should probably be done as a new type of container than having everything inside 2 controls whose sole purpose is to clip content.

**Comment by NathanLovato** [comment]
I noticed the submit button overflowing when some answer gets selected and takes more space. I think in those cases there should be no animation, because text wrapping is instant, causing an instant change in the parent container(s).

So to me the way it works now is good when submitting or skipping the quiz, but it shouldn't animate like that when selecting answers.

**Comment by mathmods** [comment]
Hmm. I did notice that as well. I can forcefully change the size if the detected change comes from the answer list and not anything else. (Or just disable animations for the choice container - though showing a hint would become instant as well in that case.)

**Comment by mathmods** [comment]
@NathanLovato The latest commit should address this. It looks for if the help labels visibility changed, if not just resize instantaneously.

**Comment by NathanLovato** [comment]
Thank you so much for your contribution! It's a most welcome improvement.

**Pull request merged**
